// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {models} from '../models';

export function ApiDispatch(arg1:string,arg2:string,arg3:string,arg4:Array<number>):Promise<main.APIDispatchResult>;

export function DesktopAudioPause():Promise<void>;

export function DesktopAudioPlay(arg1:number,arg2:number):Promise<void>;

export function DesktopAudioResume():Promise<void>;

export function DesktopAudioSeekMs(arg1:number):Promise<void>;

export function DesktopAudioStop():Promise<void>;

export function DesktopExportDatasetZip(arg1:number):Promise<string>;

export function DesktopImportFromPaths(arg1:number,arg2:Array<string>):Promise<Array<models.AudioFile>>;

export function DesktopOpenLibraryFolder():Promise<string>;

export function DesktopPickAndImportFiles(arg1:number):Promise<Array<models.AudioFile>>;

export function DesktopReadAudioFileForWaveform(arg1:number):Promise<main.DesktopAudioFileBytes>;
