// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApiDispatch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ApiDispatch'](arg1, arg2, arg3, arg4);
}

export function DesktopAudioPause() {
  return window['go']['main']['App']['DesktopAudioPause']();
}

export function DesktopAudioPlay(arg1, arg2) {
  return window['go']['main']['App']['DesktopAudioPlay'](arg1, arg2);
}

export function DesktopAudioResume() {
  return window['go']['main']['App']['DesktopAudioResume']();
}

export function DesktopAudioSeekMs(arg1) {
  return window['go']['main']['App']['DesktopAudioSeekMs'](arg1);
}

export function DesktopAudioStop() {
  return window['go']['main']['App']['DesktopAudioStop']();
}

export function DesktopExportDatasetZip(arg1) {
  return window['go']['main']['App']['DesktopExportDatasetZip'](arg1);
}

export function DesktopImportFromPaths(arg1, arg2) {
  return window['go']['main']['App']['DesktopImportFromPaths'](arg1, arg2);
}

export function DesktopOpenLibraryFolder() {
  return window['go']['main']['App']['DesktopOpenLibraryFolder']();
}

export function DesktopPickAndImportFiles(arg1) {
  return window['go']['main']['App']['DesktopPickAndImportFiles'](arg1);
}

export function DesktopReadAudioFileForWaveform(arg1) {
  return window['go']['main']['App']['DesktopReadAudioFileForWaveform'](arg1);
}
